delete from tablas where idtabla='cuestionario_opera_cnbv2023';
insert into tablas(idtabla, idelemento, nombre, dato2) values('cuestionario_opera_cnbv2023',1,'Captación: Cuentas a la vista','110');
insert into tablas(idtabla, idelemento, nombre, dato2) values('cuestionario_opera_cnbv2023',2,'Captación: Cuentas a plazo','200,201,205');
insert into tablas(idtabla, idelemento, nombre, dato2) values('cuestionario_opera_cnbv2023',3,'Captación: Cuentas de ahorro',null);
insert into tablas(idtabla, idelemento, nombre, dato2) values('cuestionario_opera_cnbv2023',5,'Cuentas concentradoras de enti en otras ent fin',null);
insert into tablas(idtabla, idelemento, nombre, dato2) values('cuestionario_opera_cnbv2023',6,'Captación: Depósitos en garantía',null);
insert into tablas(idtabla, idelemento, nombre, dato2) values('cuestionario_opera_cnbv2023',7,'Cartera de crédito: Crédito con garantía liq',null);
insert into tablas(idtabla, idelemento, nombre, dato2) values('cuestionario_opera_cnbv2023',8,'Cartera de crédito: Comercial','3111, 30101, 30102, 30103, 30104, 30112, 30121, 30122, 30201, 30202, 30212, 30501, 30502, 30512 ,30513');
insert into tablas(idtabla, idelemento, nombre, dato2) values('cuestionario_opera_cnbv2023',9,'Cartera de crédito: Factoraje financiero','30701, 30702, 30703');
insert into tablas(idtabla, idelemento, nombre, dato2) values('cuestionario_opera_cnbv2023',10,'Cartera de crédito: Consumo',' 30301, 30302, 30303, 30304, 30305, 30322, 30402, 30410, 30411');
insert into tablas(idtabla, idelemento, nombre, dato2) values('cuestionario_opera_cnbv2023',11,'Cartera de crédito: Arrendamiento financiero',null);
insert into tablas(idtabla, idelemento, nombre, dato2) values('cuestionario_opera_cnbv2023',12,'Cartera de crédito: Vivienda','30601, 30602');
insert into tablas(idtabla, idelemento, nombre, dato2) values('cuestionario_opera_cnbv2023',13,'Cartera de crédito: Puente',null);
insert into tablas(idtabla, idelemento, nombre, dato2) values('cuestionario_opera_cnbv2023',21,'Servicio: Compra de moneda extranjera Comi Naci',null);
insert into tablas(idtabla, idelemento, nombre, dato2) values('cuestionario_opera_cnbv2023',22,'Mercado Cambiario: Compra Venta de divisas en efec',null);
insert into tablas(idtabla, idelemento, nombre, dato2) values('cuestionario_opera_cnbv2023',23,'Mercado Cambiario: Compra Venta de divisas trans',null);
insert into tablas(idtabla, idelemento, nombre, dato2) values('cuestionario_opera_cnbv2023',25,'Mercado Cambiario: Compra Venta de div che terri',null);
insert into tablas(idtabla, idelemento, nombre, dato2) values('cuestionario_opera_cnbv2023',26,'Mercado Cambiario: Compra Venta de div chee extra',null);
insert into tablas(idtabla, idelemento, nombre, dato2) values('cuestionario_opera_cnbv2023',27,'Servicio: Órdenes de pago nacionales',null);
insert into tablas(idtabla, idelemento, nombre, dato2) values('cuestionario_opera_cnbv2023',28,'Servicio: Órdenes de pago internacionales',null);
insert into tablas(idtabla, idelemento, nombre, dato2) values('cuestionario_opera_cnbv2023',29,'Servicios: Venta y recargas de tarjetas prepagadas',null);
insert into tablas(idtabla, idelemento, nombre, dato2) values('cuestionario_opera_cnbv2023',33,'Mercado Cambiario: Contra_Comp Venta divs tran int',null);
insert into tablas(idtabla, idelemento, nombre, dato2) values('cuestionario_opera_cnbv2023',34,'Préstamo de Socios',null);
