-- public.tipo_reg_451 definition

-- DROP TYPE public.tipo_reg_451 CASCADE;

CREATE TYPE public.tipo_reg_451 AS (
	clave_subreporte text,
	municipio text,
	estado text,
	identificador text,
	personalidad_juridica int4,
	nombre text,
	apaterno text,
	amaterno text,
	rfc text,
	curp text,
	genero text,
	credito text,
	sucursal text,
	clasificacion_destino text,
	producto_credito varchar(60),
	fecha_disposicion text,
	fecha_vencimiento text,
	modalidad_pago int4,
	monto_original text,
	frecuencia_pago_capital text,
	frecuencia_pago_interes text,
	tasa_io text,
	fecha_ultimo_pago_capital text,
	monto_ultimo_pago_capital text,
	fecha_ultimo_pago_interes text,
	monto_ultimo_pago_interes text,
	fecha_primara_amortizacion_no_cubierta text,
	monto_condonacion text,
	fecha_condonacion text,
	dias_mora text,
	tipo_credito text,
	situacion_contable text,
	capital text,
	io text,
	im text,
	io_vencido_fuera_valance text,
	im_vencido_fuera_valance text,
	interes_refinanciado text,
	saldo_insoluto text,
	acreditado_relacionado text,
	cartera_fines_calificacion text,
	calificacion_deudor text,
	cal_parte_cubierta text,
	cal_parte_expuesta text,
	monto_estimacion_parte_cubierta text,
	monto_estimacion_parte_expuesta text,
	e_p_a_interes_devengado_cartera_vencida text,
	e_p_a_riesgos_oparativos_sic text,
	e_p_a_cnbv text,
	fecha_consulta_sic text,
	clave_prevencion text,
	garantia_liquida text,
	garantia_hipotecaria text);