--public.tipo_sai_movimientos_acumulados_superiores_v3 definition

--DROP TYPE public.tipo_sai_movimientos_acumulados_superiores_v3;

CREATE TYPE public.tipo_sai_movimientos_acumulados_superiores_v3 AS (
	numero_socio varchar,
	s1 varchar,
	nombre varchar,
	s2 varchar,
	actividad_pld varchar,
	s3 varchar,
	fecha_de_nacimiento varchar,
	s4 varchar,
	identificacion_oficial varchar,
	s5 varchar,
	nacionalidad varchar,
	s6 varchar,
	pais_de_nacimiento varchar,
	s7 varchar,
	clave_oficial varchar,
	s8 varchar,
	estado varchar,
	s9 varchar,
	municipio varchar,
	s10 varchar,
	colonia varchar,
	s11 varchar,
	calle varchar,
	s12 varchar,
	num_ext varchar,
	s13 varchar,
	num_int varchar,
	s14 varchar,
    efectivo integer,
	s15 varchar,
	fechamov timestamp,
	s16 varchar,
	sucursal varchar,
    s17 varchar,
    suma integer);