INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('111097','Cultivo de soya','111097');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('129024','Cultivo de semillas oleaginosas, excepto soya','129024');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('131011','Cultivo en viveros, cultivos no alimenticios en invernaderos y floricultura','131011');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('149014','Otros cultivos','149014');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('191015','Construcción de obras para el tratamiento, distribución y suministro de agua, drenaje y riego','191015');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('211011','Explotación de bovinos para carne','211011');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('311019','Viveros forestales y recolección de productos forestales','311019');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('312017','Tala de árboles','312017');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('400002','Pesca','400002');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('459025','Acuicultura animal','459025');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('1300003','Minería de otros minerales metálicos','1300003');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('1439018','Minería de otros minerales no metálicos','1439018');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('2000008','Elaboración de otros alimentos','2000008');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('2012011','Servicios de empacado y etiquetado','2012011');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('2049022','Comercio al por mayor de embutidos','2049022');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('2051019','Elaboración de leche y derivados lácteos','2051019');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('2061034','Preparación y envasado de pescados y mariscos','2061034');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('2071017','Elaboración de pan y otros productos de panadería','2071017');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('2091015','Elaboración de almidones, aceites y grasas vegetales comestibles','2091015');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('2093011','Elaboración de tortillas de maíz y molienda de nixtamal','2093011');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('2094019','Elaboración de botanas','2094019');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('2097013','Elaboración de helados y paletas','2097013');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('2099043','Comercio al por mayor de otros alimentos','2099043');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('2100006','Elaboración de refrescos y hielo, y purificación de agua','2100006');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('2313021','Acabado de fibras, hilados, hilos y telas','2313021');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('2400000','Confección de ropa de materiales textiles','2400000');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('2431021','Confección de cortinas, blancos y similares','2431021');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('2611011','Aserrado y conservación de la madera','2611011');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('2612019','Fabricación de productos de madera para la construcción','2612019');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('2639039','Fabricación de otros productos de madera','2639039');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('2700004','Fabricación de cocinas','2700004');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('2822014','Fabricación de envases de cartón','2822014');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('2900000','Industrias conexas a la impresión','2900000');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('3051026','Comercio al por mayor de productos farmacéuticos','3051026');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('3061025','Fabricación de jabones, limpiadores y dentífricos','3061025');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('3099042','Comercio al por mayor de materiales de desecho','3099042');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('3200003','Fabricación de hules y resinas sintéticos','3200003');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('3221017','Fabricación de bandas y mangueras de hule y de plástico','3221017');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('3229045','Fabricación de otros productos de plástico','3229045');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('3411022','Industria básica del hierro y del acero','3411022');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('3412020','Fabricación de otros productos de hierro y acero de material comprado','3412020');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('3413010','Fabricación de tubos y postes de hierro y acero de material comprado','3413010');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('3429017','Laminación secundaria de otros metales no ferrosos','3429017');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('3531010','Fabricación de estructuras metálicas','3531010');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('3596014','Fabricación de otros productos metálicos','3596014');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('3599133','Fabricación de productos metálicos forjados y troquelados','3599133');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('3600005','Maquinado de piezas metálicas para maquinaria y equipo en general','3600005');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('3621027','Fabricación de maquinaria y equipo para la industria metalmecánica','3621027');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('3631018','Fabricación de maquinaria y equipo para las industrias manufactureras, excepto la metalmecánica','3631018');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('3632016','Comercio al por mayor de maquinaria y equipo para la construcción y la minería','3632016');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('3697010','Fabricación de sistemas de aire acondicionado, calefacción y de refrigeración industrial y comercial','3697010');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('3699024','Reparación mecánica y eléctrica de automóviles y camiones','3699024');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('3700003','Fabricación de componentes electrónicos','3700003');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('3711018','Fabricación de equipo de generación y distribución de energía eléctrica','3711018');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('3799014','Fabricación de anuncios','3799014');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('3811016','Fabricación de automóviles y camionetas','3811016');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('3832012','Fabricación de equipo aeroespacial','3832012');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('3900009','Fabricación de maquinaria y equipo para otras industrias manufactureras','3900009');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('3932010','Comercio al por mayor de artículos de joyería y otros accesorios de vestir','3932010');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('4111936','Colocación de pisos cerámicos y azulejos','4111936');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('4111952','Trabajos de albañilería','4111952');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('4112017','Edificación de inmuebles comerciales, institucionales y de servicios','4112017');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('4113015','Edificación de naves y plantas industriales','4113015');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('4121018','Construcción de vías de comunicación','4121018');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('4121034','División de terrenos y construcción de obras de urbanización','4121034');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('4193017','Construcción de obras de generación y conducción de energía eléctrica y telecomunicaciones','4193017');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('4199015','Otras construcciones de ingeniería civil u obra pesada','4199015');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('4222014','Instalaciones eléctricas en construcciones','4222014');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('4229010','Instalaciones hidrosanitarias, de gas, aire acondicionado y calefacción','4229010');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('4293015','Instalación de productos de carpintería','4293015');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('4299013','Otras instalaciones y equipamiento en construcciones','4299013');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('5011010','Suministro de energía eléctrica','5011010');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6100002','Comercio al por mayor de bebidas','6100002');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6111017','Comercio al por menor de semillas y granos alimenticios, especias y chiles secos','6111017');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6112015','Comercio al por mayor de frutas y verduras frescas','6112015');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6122014','Comercio al por mayor de carnes','6122014');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6125018','Comercio al por mayor de huevo','6125018');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6131023','Comercio al por menor en tiendas de abarrotes, ultramarinos y misceláneas','6131023');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6132013','Comercio al por mayor de dulces y materias primas para repostería','6132013');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6132021','Comercio al por mayor de semillas y granos alimenticios, especias y chiles secos','6132021');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6132047','Comercio al por menor de leche procesada, otros productos lácteos y embutidos','6132047');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6139019','Comercio al por mayor de cigarros, puros y tabaco','6139019');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6211023','Comercio al por mayor de ropa','6211023');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6212013','Comercio al por mayor de calzado','6212013');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6231021','Comercio al por mayor de artículos de perfumería','6231021');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6233019','Comercio al por mayor de artículos de papelería','6233019');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6300008','Comercio al por mayor de electrodomésticos menores y aparatos de línea blanca','6300008');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6311039','Alquiler de aparatos eléctricos y electrónicos para el hogar','6311039');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6312011','Comercio al por menor de muebles para el hogar y otros enseres domésticos','6312011');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6322010','Comercio al por menor de artículos para la decoración de interiores','6322010');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6329016','Alquiler de otros artículos para el hogar','6329016');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6400006','Comercio al por mayor de abarrotes','6400006');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6411011','Comercio al por menor en tiendas de autoservicio','6411011');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6515011','Comercio al por menor de aceites y grasas lubricantes, aditivos y similares','6515011');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6600002','Comercio al por mayor de materias primas para otras industrias','6600002');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6622022','Comercio al por menor de artículos de ferretería, tlapalería y vidrios','6622022');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6629010','Comercio al por mayor de materiales para la construcción, excepto de madera','6629010');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6711015','Servicios relacionados con la agricultura','6711015');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6712013','Servicios relacionados con la minería','6712013');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6721036','Comercio al por menor de computadoras, teléfonos y otros aparatos de comunicación','6721036');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6722012','Comercio al por mayor de maquinaria, mobiliario y equipo de uso general','6722012');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6815015','Comercio al por menor de partes y refacciones para automóviles, camionetas y camiones','6815015');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('6999041','Comercio al por mayor de artículos desechables','6999041');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('7111016','Otro transporte terrestre de pasajeros','7111016');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('7119010','Transporte escolar y de personal','7119010');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('7123011','Alquiler de camiones de carga, autobuses y remolques sin chofer','7123011');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('7129019','Intermediación al por menor','7129019');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('7300007','Otros servicios relacionados con el transporte aéreo','7300007');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('7400005','Servicios de mensajería y paquetería foránea','7400005');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('7500003','Otros servicios relacionados con el transporte','7500003');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('7511018','Almacenamiento general sin instalaciones especializadas','7511018');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('7600001','Comercio al por mayor por medios masivos de comunicación y otros medios','7600001');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('7611016','Edición de software, excepto a través de Internet','7611016');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('7613004','Reventa de servicios de telecomunicaciones','7613004');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('7613012','Otros servicios de telecomunicaciones','7613012');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8100000','Compañías especializadas en seguros de vida','8100000');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8211013','Asesoría en inversiones','8211013');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8211039','Casas de bolsa','8211039');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8219017','Agentes, ajustadores y gestores de seguros y fianzas','8219017');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8300006','Preparación de terrenos para la construcción','8300006');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8312019','Alquiler sin intermediación de viviendas y otros inmuebles','8312019');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8313017','Inmobiliarias y corredores de bienes raíces','8313017');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8411019','Notarías públicas','8411019');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8412017','Bufetes jurídicos','8412017');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8413015','Servicios de contabilidad, auditoría y servicios relacionados','8413015');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8414013','Servicios de arquitectura','8414013');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8419013','Servicios de alquiler de marcas registradas, patentes y franquicias','8419013');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8421018','Edición de revistas y otras publicaciones periódicas, excepto a través de Internet','8421018');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8422016','Agencias de anuncios publicitarios','8422016');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8424012','Servicios de apoyo para efectuar trámites legales','8424012');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8426026','Agencias de relaciones públicas','8426026');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8427016','Reparación y mantenimiento de maquinaria y equipo agropecuario, industrial, comercial y de servicios','8427016');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8429012','Otros servicios profesionales, científicos y técnicos','8429012');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8429020','Dirección de corporativos y empresas','8429020');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8500002','Centros generales de alquiler','8500002');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8511017','Alquiler de maquinaria y equipo para construcción, minería, actividades forestales y transporte, excepto terrestre','8511017');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8519011','Alquiler de otra maquinaria y equipo industrial, comercial y de servicios','8519011');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8524010','Alquiler de automóviles sin chofer','8524010');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8611015','Hoteles y moteles, excepto hoteles con casino','8611015');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8619019','Pensiones y casas de huéspedes, y departamentos y casas amueblados con servicios de hotelería','8619019');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8700008','Servicios de preparación de alimentos para ocasiones especiales','8700008');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8711021','Restaurantes con servicio de meseros','8711021');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8800006','Otros servicios recreativos','8800006');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8814015','Clubes deportivos, balnearios y centros de acondicionamiento físico','8814015');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8827018','Deportistas y equipos deportivos profesionales y semiprofesionales','8827018');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8900004','Otros servicios personales','8900004');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8911019','Otros servicios de reparación y mantenimiento de automóviles y camiones','8911019');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8914013','Hojalatería, tapicería y otras reparaciones a la carrocería de automóviles y camiones','8914013');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8929020','Confección de accesorios de vestir','8929020');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8933013','Salones y clínicas de belleza y peluquerías','8933013');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8934011','Lavanderías y tintorerías','8934011');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8935019','Otros servicios de limpieza','8935019');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8942014','Diseño y decoración de interiores','8942014');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('8944028','Otros servicios de apoyo secretarial y similares','8944028');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('9112012','Escuelas de educación preescolar','9112012');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('9113010','Escuelas de educación secundaria general','9113010');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('9119018','Escuelas de educación secundaria técnica','9119018');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('9121013','Escuelas de idiomas','9121013');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('9122011','Escuelas para la capacitación de ejecutivos','9122011');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('9129017','Escuelas que combinan diversos niveles de educación','9129017');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('9191016','Servicios de investigación y desarrollo en ciencias físicas, de la vida e ingeniería','9191016');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('9211012','Hospitales generales','9211012');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('9212010','Consultorios médicos','9212010');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('9213018','Consultorios dentales','9213018');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('9214016','Laboratorios de pruebas','9214016');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('9312018','Asociaciones, organizaciones y cámaras de productores, comerciantes y prestadores de servicios','9312018');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('9331018','Asociaciones y organizaciones religiosas','9331018');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('9400003','Actividades administrativas federales de instituciones de bienestar social','9400003');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('10000001','Sitios históricos','10000001');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('10000036','Servicios de protección y custodia mediante el monitoreo de sistemas de seguridad','10000036');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('10000041','Comercio al por menor de productos farmacéuticos y naturistas','10000041');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('10000051','Comercio al por menor de combustibles','10000051');
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) VALUES ('10000056','Intermediación al por mayor','10000056');


------ ACTIVIDADES PENDIENTES NUEVAS SEGUN JESUS
INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) 
VALUES ('112128','Cultivo de hortalizas','112128');

INSERT INTO actividades_economicas_pld (id_actividad,descripcion,idx) 
VALUES ('8922016','Reparación y mantenimiento de equipo electrónico y de equipo de precisión','8922016');