-- public.tipo_reg_453 definition

-- DROP TYPE public.tipo_reg_453 CASCADE;

CREATE TYPE public.tipo_reg_453 AS (
	clave_subreporte text,
	numerosocio text,
	per_jur numeric,
	nombre text,
	appaterno text,
	apmaterno text,
	rfc text,
	curp varchar(18),
	genero numeric,
	numerocredito text,
	sucursal int4,
	clasificacioncredito text,
	productocredito text,
	fechaotorgamiento text,
	fecha_vencimiento text,
	modalidad_pago numeric,
	montooriginal text,
	fecha_ultimo_pago_capital text,
	monto_ultimo_pago_capital text,
	fecha_de_ultimo_pago_interes text,
	monto_ultimo_pago_interes text,
	fecha_primera_amortizacion_no_cubierta text,
	diasmora text,
	tipocredito text,
	saldoinsolutocapital text,
	interesesvencidos text,
	montoim text,
	interesesrefinanciados text,
	monto_castigo text,
	montocondonacion_quita_bonificacion text,
	fechacastigo text,
	personarelacionada text,
	montodeestimacionespreventivas text,
	claveprevencion int4,
	fecha_sic text,
	tipocobranza text,
	montodegarantialiquida text,
	montodegarantiahipotecaria text,
    poliza text);