-- public.tipo_reg_841 definition
DROP FUNCTION IF EXISTS public.reg_841cerro() CASCADE;
DROP TYPE IF EXISTS public.tipo_reg_841cerro CASCADE;
-- DROP TYPE public.tipo_reg_841;

CREATE TYPE public.tipo_reg_841cerro AS (
	formulario text,
	numero_de_identificacion text,
	tipo_de_socio text,
	nombre_razon_o_denominacion_social text,
	apellido_paterno_del_socio text,
	apellido_materno_del_socio text,
	rfc_del_socio varchar,
	curp_del_acreditado_persona_fisica text,
	genero text,
	fechanacimiento_o_constitucion_de_persona_moral text,
	codigo_postal_del_domicilio varchar(6),
	localidad_del_domicilio text,
	estado_del_domicilio text,
	pais_del_domicilio text,
	numero_de_certificados_de_aportacion_ordinaria text,
	monto_de_certificados_de_aportacion_ordinaria text,
	numero_de_certificados_exedentes_o_voluntarios text,
	monto_de_certificados_exedentes_o_voluntarios text,
	numero_de_contrato text,
	numero_de_cuenta text,
	nombre_de_sucursal_que_opera_el_deposito int4,
	fecha_de_contratacion text,
	tipo_de_producto text,
	tipo_de_modalidad text,
	tasa_de_rendimiento_anual text,
	moneda text,
	plazo text,
	fecha_de_vencimiento text,
	saldo_de_la_cuenta_al_inicio_del_periodo text,
	monto_de_deposito_de_dinero text,
	monto_del_retiro_de_dinero text,
	interes_devengados_no_pagado_en_el_periodo text,
	saldo_de_la_cuenta_al_final_del_periodo text,
	fecha_del_ultimo_movimiento text,
	tipo_de_apertura_de_cuenta text,
	idorigen int4,
	idgrupo int4,
	idsocio int4,
    fecha_ingreso text,
	actividad_economica  text,
	clasificacion_riesgo text,
	estatus                                             text,
	nombre_producto                                     text,
	saldo_promedio                                      text,
	numero_reinversiones                                text
	);